### ISSUE TITLE
Pi4: Garbled sound on internal jack

### ISSUE THREAD

**Issue by KajFRasmussen** [JuliusCode/MP4MUSEUM#1]
I am working on a project with the new PI4 hardware platform combined with MP4MUSEUM Version 4.20, and have noticed that sound output on the internal 3,5 mm jack port is very tinny and overdriven. It seems to be a driver issue with the internal sound hardware, as there is no trouble when booting into an updated Raspian. Sound output is fine via HDMI.
Is there hope that this will be fixed in an upcoming version of the 4th genereation images? 
I will test the problem on Version 5 beta ASAP...

**Comment by KajFRasmussen** [comment]
On version 5 beta there is no sound at all from the jack out of the box. 
Via HDMI sound also works fine here though.

**Comment by JuliusCode** [comment]
on v4 the playback engine is omxplayer, which sends audio directly to hdmi and analog out. in general i don't recommend using the analog out, there are a few things one can do via config.txt but overall it's not great

v5 beta uses vlc and alsa output, so it is going only to hdmi per default. you need to change your alsa conf or hack the python script to redirect vlc output to your interface.

try using a DAC like hifiberry or an usb soundcard if you need analog audio would be my best advice

**Comment by KajFRasmussen** [comment]
Thanks for the swift answer!
Indeed the internal sound port is not in any way the greatest, but it's there, and in some cases nearer to the speakers than projectors and in some cases TV´s.
If no other road to salvation apears, and I cant bear fiddling with the code, I will indeed try USB a sound card (already found one that was NOT supported), or a DAC.
Thanks for a great project by the way :-)

**Comment by JuliusCode** [comment]
just one more note: hdmi and headphones out are two different devices on raspi. so you can still decide to use it if you follow the instructions on how to change audio output via alsa.

J.
