### ISSUE TITLE
Download size

### ISSUE THREAD

**Issue by jonnyscholes** [JuliusCode/MP4MUSEUM#13]
Love the project! I'm trying to download the V5 .img from https://mp4museum.org/download/ the file size is much larger than 1.2GB noted. Is that expected? My download is at 2.5GB and counting...

**Comment by jonnyscholes** [comment]
Downloading v5 beta 3 works correctly (at this URL http://mp4museum.org/mp4museum-v5beta.img.zip).

It looks like the server isn't sending back a content length when serving the v5 img (https://mp4museum.org/mp4museum-v5.img.gz), so browsers can't correctly close the connection. 

Does the V5 download link finish downloading for you @JuliusCode?

Thanks for your work on this project 🙏

**Comment by JuliusCode** [comment]
Hi Jonny,

thanks for your message! while i‘ve had one email so far regarding this problem, i could not replicate it on my system, i tried firefox and safari on mac. 
after you opened the ticket i contacted my provider (it‘s on shared hosting) but have not heard back from them. from the stats it seems it is affecting only a fraction of people. maybe you could help by providing info on the operating system and browser you are using?

best, Julius.

**Comment by jonnyscholes** [comment]
Hi Julius,

I managed to get it working using Firefox, however for posterity I tried using the following and it didn't work:

OS: MacOS 11.6.4
Safari (14.1.2) - Got the correct size, but continued downloading past that size (2.8gb before I cancelled on one try)
Chrome (98.0.4758.102) - Didn't show a size, downloaded until I cancelled (got to 5.5gb on one try)

I also tried `curl` (7.64.1), but had the same behaviour as Chrome.

Thanks for your assistance! V5 is brilliant 👌

**Comment by JuliusCode** [comment]
Hi,

i tried safari on my other mac running os 12, it gave the same error you have, downloading past the pre announced size. i have no idea why…

so i started from scratch and made a new packed image, this time went for regular zip extension. size is about the same, it‘s on the website now.

if you would give me feedback if that resolved the issue, that would be nice.

best, Julius.

**Comment by jonnyscholes** [comment]
Hi Julius,

I've just tried the new link, and it works! Thanks for looking into this 🙏

Cheers,
Jonny
