### ISSUE TITLE
Gap Between Loops

### ISSUE THREAD

**Issue by pwsherman** [JuliusCode/MP4MUSEUM#14]
This is awesome for 4K! The only problem is the 1/2 a second gap at the end of a cycle. I've tried an off-the-shelf solutions as well (Neumi Atom 4K) and it also has a gap. The HD OMXPlayer Pi build has a slight delay but not a black screen.

Any chance in the future for a no-gap solution? I read that VLC for the Pi is not ready for prime time but I don't understand why this hasn't been solved, even commercially.

Thanks for your work on this.

**Comment by JuliusCode** [comment]
hi,
is the filename „loop.mp4“? other than that, my guess it‘s an encoding issue. 

J.

**Comment by pwsherman** [comment]
Thank you!! Naming the file loop.mp4 seems to have fixed it! I knew I saw that in your documentation somewhere but I couldn't find it on review. Thanks so much!
