### ISSUE TITLE
master/slave interconnection

### ISSUE THREAD

**Issue by MLJ66** [JuliusCode/MP4MUSEUM#17]
Hello,

How do you interconnect many slaves with master on differents network? I don't understand how configure the slaves, because when it's mp4museumsync I don't have scrypt.

Thank You,

**Comment by JuliusCode** [comment]
Hi,
the interconnection is via ip networking, the main player sends out a clock via beoadcast. so in order to work the players need to be in the same ip space, like 10.0.0.X
on this version there is no startup script. the omxplayer-sync is started as a service.

best, Julius.
