### ISSUE TITLE
mp4museum without screen

### ISSUE THREAD

**Issue by peterboogle** [JuliusCode/MP4MUSEUM#19]
Hi, and thanks for your great work.

I would like to create a standalone audio player
is it possible to use MP4MUSEUM without connecting a screen? I try to play .WAV file on raspberry pi 3 (headphone output).
It works perfectly when the hdmi screen is plugged in, but if I start raspberry without screen, it does not work anymore.
I tried to modify the config.txt file, without success. 

can you help me?

Thanks

Pierre

**Comment by JuliusCode** [comment]
Dear Peter,

for using analog out, may i suggest using a usb soundcard for better audio quality? in any case, you may redirect sound output via alsa.txt on the /boot partition, more info on the website (sound how-to). 

best, Julius.

**Comment by peterboogle** [comment]
Dear julius,
thank you for your answer, 
I have no problem with the analog output, I manage to configure the alsa.txt file, as well as adjust "alsamixer". But when i unplug the screen (HDMI TV) and reboot Raspberry, the sound file does not start anymore. As if the program was trying to connect to a video monitor, but I would like to do without.
i don't know if my question is clear, sorry for my english.

best

**Comment by JuliusCode** [comment]
If there is no monitor connected, try to substract 1 from the current value.
the other possibility is to force hdmi via config.txt, so it does not change the numbers (pointing to audio devices) when hdmi is not connected. 

could you give me feedback on these values, if it helps making it work?

with hdmi connected:
0 = hdmi
1 = analog out
2 = ext usb card (if present)

without hdmi:
0 = analog out
1 = ext card

best, Julius.

**Comment by peterboogle** [comment]
I will try this week and get back to you.

thanks a lot !

Pierre

**Comment by peterboogle** [comment]
Dear julius,
as you advised me, I modified the value 1 by 0 in alsa.txt and the sound now works on the analog output even without an hdmi screen. I tried to modify config.txt but it was my alsa.txt file that was the source of the problem. 

I ordered an external sound card, it's going to be really perfect. thanks again

best, Pierre
