### ISSUE TITLE
Issues with setting up a wifi network

### ISSUE THREAD

**Issue by scerelli** [JuliusCode/MP4MUSEUM#2]
Hi,
I just tried to flash the image of your mp4museum in 2 raspberry 3a+ the master one it's firing up a video immediatly that is not the one i put on the usb stick, i suppose is your video and i can't connect it to the wifi because if i try to kill the video it restarts.

On the slave one i logged in using the user and password you provided, I tried to connect it to the wifi using the raspberry configurator but it doesn't connect.

I also tried to manually add ssid and network password in `/etc/wpa_supplicant/wpa_supplicant.conf` but it's a readonly file, i also tried to add read and write permission in `/boot/cmdline.txt` but it is also a readonly file. 

do you have an idea and how to get around this?
thanks

**Comment by JuliusCode** [comment]
hi,
it is not meant to log in locally/via keyboard. 
to setup wifi you can place wpa_supplicant on the /boot drive after writing the image.
re-mount the filesystem as rw before making changes, see "how to hack" on the homepage.

J.

**Comment by scerelli** [comment]
Thanks @JuliusCode
