### ISSUE TITLE
Seamless loop starts not at start

### ISSUE THREAD

**Issue by minizzZ** [JuliusCode/MP4MUSEUM#20]
Hello,

For an exhibition I've been working with 10 Raspberry Pi Zero W's and your MP4Museum. The video is, you see a face, it morphs into another one and than morphs back. The thing is some (not all) of the loops don't start at the beginning, it looks like it jumps 10 seconds at the start of the loop. The specs video's are:

Length 1:20
Frame Widt x height: 1920x1080 
Data rate: 1265kbps
Total Bitrate: 1908kbps
Frame Rate 25.00 frames/second

They've been handbraked into h264 mp4 and have been put on the internal card of the pi. I use the original img, hasn't been tweaked or hacked. Also I made the video three times longer. Result was still a jump in time at the start and the rest was good.

I can send you a link of the video but via a pm because I'm not the owner of the material, but it is ok to send it. 

Do you have any idea?

**Comment by minizzZ** [comment]
I will send you a WeTransfer with the files via email

**Comment by JuliusCode** [comment]
hey, i was able to take a look at your file today.

it loops well on my test hardware (v5 on raspbery pi 1), if renamed to "loop.mp4". maybe switch sd cards?

regarding the encoding, there were unused audio tracks in the file and i did re-encode for testing with the "vimeo/youtube hq 1080p" setting and even with no audio tracks, the file came out twice the size. but it resulted in no change regarding playback on the raspi, both was fine.

best, Julius.
