### ISSUE TITLE
Sync Version is not compatible to newer pi4

### ISSUE THREAD

**Issue by johnteh00** [JuliusCode/MP4MUSEUM#23]
When I try to run the Master/Slave Version on a Pi that has previously run the newest 5.5 standalone mp4museum those PIs will not finish booting and register the following error: "Start4.elf: is not compatible This board requires newer software". Seems like something gets updated on the board and is then no longer compatible.

**Comment by JuliusCode** [comment]
Hi, so i would expect this error from newer boards which came out after the operating system that the sync version is running on, it sounds like using a current operating system (like in mp4museum 5.5) upgrades the firmware without notice. 
could you add some info regarding the board you are using? 
also, if you look up "raspberry firmware downgrade" there are tutorials how to get back to older software, this would involve booting standard raspbian lite from another card, if that is something you would like to try?

i any case, please keep me posted if you have new findings.

best, Julius.

**Comment by johnteh00** [comment]
thanks for your answer, Julius. To which firmware version should I downgrade, you think? My Raspberries are all Pi 4 with 2GB of ram.

**Comment by johnteh00** [comment]
I tried downgrading it to an early 2020 firmware. But then I get the same start4.elf error. That says the firmware is to old for my board, it needs a newer version. I tried replacing all 8 .elf files in the MP4 Master Boot partition with ones from a current and clean Raspberry OS install. But then the Pi boots to a Kernal panic.

**Comment by JuliusCode** [comment]
Hi,
the Pi4 that you are using, are they made after april of 2021? i think they have changed hardware then, maybe this is why it won‘t boot.

**Comment by johnteh00** [comment]
Checking with CPU Info, all of them are "Raspberry Pi 4 Model B Rev 1.5"

**Comment by JuliusCode** [comment]
the only pi4 i have is of the first series (wich has the usb c problem that got fixed in v1.2), so i can‘t confirm this, but my best guess is that is why yours will not boot.
one thing to try would be to login, remount the linux partition and upgrade the boot part of the system with apt-get upgrade. but honestly, it‘s a bit of a shot in the dark :/

best, Julius.

**Comment by johnteh00** [comment]
But how can I login when it doesn't boot?

**Comment by JuliusCode** [comment]
my bad, i incorrectly assumed you would have access to other hardware. i will try a few things once i am done with current payjobs.
