### ISSUE TITLE
sound card with mp4museum sync

### ISSUE THREAD

**Issue by peterboogle** [JuliusCode/MP4MUSEUM#24]
Dear julius,

i use a DAC iQaudio pro (for balanced output). It works well with mp4museum V5.5 and alsa.txt file. But it doesn't work with mp4museum sync version.

however the card is correctly detected :

      pi@mp4museum:~ $ aplay -l
      **** List of PLAYBACK Hardware Devices ****
      card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
        Subdevices: 4/4
        Subdevice #0: subdevice #0
        Subdevice #1: subdevice #1
        Subdevice #2: subdevice #2
        Subdevice #3: subdevice #3
      card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
        Subdevices: 4/4
        Subdevice #0: subdevice #0
        Subdevice #1: subdevice #1
        Subdevice #2: subdevice #2
        Subdevice #3: subdevice #3
      card 2: IQaudIODAC [IQaudIODAC], device 0: IQaudIO DAC HiFi pcm512x-hifi-0 [IQaudIO DAC HiFi pcm512x-hifi-0]
        Subdevices: 1/1
        Subdevice #0: subdevice #0
      pi@mp4museum:~ $ 

I can also access the iQaudio card settings in alsamixer, but from the menu "sudo raspi-config", I can't select it. 

is it possible to change the audio output in mp4museum Sync ?

Thanks so much
best, Pierre.

**Comment by JuliusCode** [comment]
Dear Pierre,

sorry to say that there is, at least to my knowledge, no way to route audio from the sync version other than hdmi or analog out. omxplayer-sync is quite old now and has seen no updates in years, i am still looking for a replacement.

if you need high quality audio, i can only suggest to use hdmi out and get a audio de-embedder. it will take the audio stream from hdmi and usually provides spdif digital and/or stereo analog output.

best, Julius.

**Comment by peterboogle** [comment]
thank you for your advice, I wish you all the best for your projects

pierre
