### ISSUE TITLE
Master Sync Video Partition Resizing to Fill SD Card

### ISSUE THREAD

**Issue by thesoundofthesound** [JuliusCode/MP4MUSEUM#25]
The Master Sync Video partition doesn't seem to be resizing to fill the empty space on the SD Card. I have not had this problem with the slave sync image, it resized to fill the SD card just fine. Is there a way of expanding the Video partition easily? Doesn't seem to work for me when following instructions on how to use parted.

**Comment by JuliusCode** [comment]
Hi,
it‘s been a while since i‘ve made those images, but the method was the same for both versions. 
when you expand the space it might be necessary to change the filesystem, i think it was only fat32 so it won‘t accept files larger than 4gb. 

best, Julius.

**Comment by thesoundofthesound** [comment]
Thanks for the quick reply! 

Is there an easy way of changing the file system so it can be expanded? Is it just a case of formatting the SD card to a different one (e.g. exFAT) and then flashing the image, or would I need to that by SSHing into the Pi and doing it that way?

**Comment by JuliusCode** [comment]
to resize partitions and formatting i use gparted on raspbian. this way you can choose just one partition to format, instead of deleting the whole card in the process. 

just after formatting it is necessary to edit the fstab on the linux partition, the type of filesystem has to be specified there or it will not mount on boot. 

i hope this helps you to find some tutorials online, myself being not the best tutor for things in linux ;)

cheers! Julius.

**Comment by johnteh00** [comment]
I have the same problem with the 5.5 standalone. I'm using 64gb cards but the media partition only shows 12GB of usable space. The partition is formated as ExFat.

**Comment by JuliusCode** [comment]
the partition is sized so it can be written, including the system, on a 16gig card.
to use any additional space would need manually resizing the partition, it will not auto-expand.

**Comment by johnteh00** [comment]
thanks Julian, I got it to work as you described. If anyone else looking to, I performed the following steps:

1) Installed Raspbian OS on a seperate SD card. 
2) After booting to the GUI and configuring I installed gbparted in the terminal window
```
sudo apt-get
update sudo apt-get upgrade
sudo apt-get install gparted
```
3) with the mp4museum SD card attached in a card reader I selected it from the dropdown. /SDD/…
4) If mounted, all partitions had to be unmounted. 
5) I deleted the current "media" partition and performed a "move" operation on the "root fs" partiotion that sits between media and the rest of the unallocated space. "Move" was done with the given settings. 0MB preceding. 
6) After I formated the remaining single unallocated space as ExFat with the label "media"
7) To apply all changes you have to click the checkmark and wait for a bit.

**Comment by JuliusCode** [comment]
thanks for the info! i'll pin this
