### ISSUE TITLE
I want to play videos in a particular order at startup

### ISSUE THREAD

**Issue by Valspar** [JuliusCode/MP4MUSEUM#26]
No matter what I name the file it seems the order is randomized.  How can I play a particular order by naming my files a certain way.

**Comment by JuliusCode** [comment]
hi,
to solve your issue please take a look at the documentation of the function used to sort the files 

https://docs.python.org/3/library/functions.html#sorted

best, Julius.

**Comment by reset131** [comment]
Hi, how to make 10 videos play in a particular order and loop them seamlessly? Do I have to create a playlist and loop the playlist or how do I do this? Eventually I would need to change the order. 
I am new to this I have not burn the micro card yet, but I wanted to know i this is possible and how.
Thank you!

**Comment by JuliusCode** [comment]
hi,
there is no support for playlists, also those would be handled as individual files and therefore not play seamless.
best practice would be to edit a longer file that contains all videos and try to loop that. if there is too much of a delay between playbacks (depending on encoding and hardware used), you could loop that edit in the editing process to a length of an hour or so.

best, Julius

**Comment by reset131** [comment]
Thank you Julius. Do you recommend any particular setting for encoding, or have a handbrake preset that I could use? I normally export from Davinci Resolve with the default vimeo HD settings. I just configure a model 3A+ board with mp4museum and right now puting together the videos as 1 file for the loop.
Best

**Comment by JuliusCode** [comment]
with handbrake i try the quick encoding first and increase quality from there if needed. i use resolve kind of the same way. every encode i will test on a high quality display.

especially for the older pi it is important to not just use high bitrates without good reason. performance (including looping the file) is better with bitrates only as high as necessary.

cheers!

**Comment by reset131** [comment]
got it, thank you!

**Comment by reset131** [comment]
Sorry, I forgot, a mov file with same configuration h264 would play as well, or it must to be mp4?

**Comment by JuliusCode** [comment]
i would suggest mp4, even though quicktime is generally supported, some files don‘t work properly if they contain things like rotation etc

**Comment by reset131** [comment]
Thank you Julius, today I will do the first test, have already  all the pieces together; will report back.

**Comment by JuliusCode** [comment]
great! one last hint from my side: as standard the display refresh rate is 60hz, which might result in kind of a stutter with 25p material. you could change config.txt to output 50hz or try to change framerate by generating extra frames in resolve.

best, Julius

**Comment by reset131** [comment]
thank you Julius, for now will leave it as it is, for is already in the exhibition place, I mounted the video installation a couple of hours ago, in bit I go to the openning, but, lie I daid, I have not seen anything strange so far, however I will bring my backup card with mode 33 in my pocket! So set for 25 and not for 50hz?

**Comment by JuliusCode** [comment]
if 33 is not working you could try 31 with 50hz, then every frame is send out twice. 
but it really depends on your display/projector, some will not accept a 25hz source.

**Comment by reset131** [comment]
Will report back soon. For now it is working fine as it is. Thank you for all the advice Julius and the kindness, your soft is really great.
