### ISSUE TITLE
How to bring up command line

### ISSUE THREAD

**Issue by Valspar** [JuliusCode/MP4MUSEUM#28]
I want to thank Julius for the support on this, I feel like I am getting somewhere with it.
How does one bring up the command line or the rasbi config tool when the software starts up immediately? Are there certain keys on the keyboard one has to type at boot? Like a pc?

**Comment by JuliusCode** [comment]
hi,
on the current version, try this:

boot up the player with no media to play back. should show a blank screen after the startup video.

press alt + f2 to change to console number 2

login with user pi, password mp4museum

best, Julius
