### ISSUE TITLE
VLC HTTP Interface or alternative control

### ISSUE THREAD

**Issue by zinger5** [JuliusCode/MP4MUSEUM#29]
I'm trying to work out a way to allow me to have a video which plays on a loop but by giving a user input will move to a second video and then, once that video completes, return to the original loop video. I'd like to achieve this without needing a button attached to GPIO. Is there a way to enable either a keyboard button press to achieve that, or a remote command sent over SSH or similar?

I wondered if using VLC's HTTP Interface might be an option but, whilst I can get it to show if I start a second VLC instance over SSH (using -I http --http-password foo) when I add that to mp4museum.py it doesn't seem to work. Adding the HTTP Interface as a secondary interface allows me to open the HTTP Interface on a local machine but it doesn't seem to pick up the playing file or allow remote control.

Many thanks,
Joe

**Comment by JuliusCode** [comment]
dear joe,

my apologies for the late reply, had a busy week.

regarding your project, i would suggest to change the python script to reflect your needs. there is a function that will be called by the event listener for gpio, but you could change or add to that code to react to keyboard (or serial, or http) input. 

with a „loop.mp4“ and „second.mp4“ and the quit/skip button you would have the kiosk mode you want. 

best, Julius.

**Comment by zinger5** [comment]
Thanks Julius - much appreciated. I'll see if I can figure out how to make that work!

All the best,
Joe
