### ISSUE TITLE
Beta 6 Syncing Issues

### ISSUE THREAD

**Issue by thesoundofthesound** [JuliusCode/MP4MUSEUM#31]
I've been trying to get Beta 6 to work in sync mode. I'm having no issues getting videos to loop but sync is not working. I've followed instructions exactly on the website... I'm not sure how to debug.

**Comment by thesoundofthesound** [comment]
I may have figured it out. I had to put the 'sync-leader.txt' and 'sync-player.txt' files on the USB pen. I thought these needed to be placed on the 'boot' SD card. It isn't clear which way this should be done based on instructions at https://mp4museum.org/howto-sync/

This should really be made clearer...

**Comment by JuliusCode** [comment]
hey, thanks for your feedback.
i have just released the v6 version, and updated the page to reflect the changes made to sync mode.
also, i took inspiration from your comment,  the sync-….txt can now also be placed on the boot partition.

best, Julius
