### ISSUE TITLE
Is there a way to add keybindings to play specific videos?

### ISSUE THREAD

**Issue by dvillas28** [JuliusCode/MP4MUSEUM#36]
Hello!. I want to set some of the keys of my keyboad to play specific videos (and also specific keys to pause/play the videos) for a personal project. Is there a way to do that? I know there are some python libraries that can listen to specific key-pressing. But how would I go about interrupting the current media playing if i press another key?

**Comment by JuliusCode** [comment]
hi, it seems there has been a problem with my previous answer i had made via email: 
you can remove the main loop and just call the play video subroutine via keyboard event. you might run into a problem though if you try to trigger a clip while there is one running already, as play video assumes that there is no current playback.
best, Julius.
