### ISSUE TITLE
RPI4 component + HDMI switching issue

### ISSUE THREAD

**Issue by ZiggyLever** [JuliusCode/MP4MUSEUM#38]
Hi Julius, 

I discovered a workaround for the fact that on RPI4 enable_tvout is disabled by default, and I thought I'd share it here. When tvout is enabled, this puts the Pi into composite mode for CRT playback etc, however, the automatic switching between composite and HDMI (like on the PI3s and below) doesn't work. This means you must choose either to enable or disable tvout in the code on the RPI4. 

To retain the functionality of the RPI3s, where you can select between modes on power up depending on whether the AV cable or HDMI is plugged in, I came up with a hack that used the [EDID *] function without calling a specific monitor/projector EDID number. 
I've tested this going back and forth on different HDMI destinations and composite in-between, and it works. 

Here is the code I added for this to work:

`
#enable composite out
enable_tvout=1

[EDID=*]
#HDMI force
 hdmi_force_hotplug=1
#disable composite out
enable_tvout=0

`

I hope this is useful, 

All the best

Ziggy

**Comment by JuliusCode** [comment]
dear ziggy,
thanks for your input, by any chance did you try the same config on other raspi like 1-3, a+, w?
if it is something that works universally i would be happy to include this into the default config for mp4musem.

cheers! J.

**Comment by ZiggyLever** [comment]
Hi Julius, 

I've tested an RPI3 b, which works already without the extra code I added. I think this is because the RPI4s have enable_tvout disabled by default, where as older Pis have it enabled.  If added it could be commented out so those using RPI4s can uncomment it?

Thanks again for writing the MP4Museum code! 

Best

Ziggy
