### ISSUE TITLE
XDG_RUNTIME_DIR is not set in the environment

### ISSUE THREAD

**Issue by antonellafortuna** [JuliusCode/MP4MUSEUM#39]
after playing every video i have this line in output ERROR:XDG_RUNTIME_DIR is not set in the environment.
What's the problem? How can i solve it?

**Comment by JuliusCode** [comment]
hi,
it‘s an error with vlc to which i do not have a fix. vlc actually outputs a lot of stuff on the console but as long as playback works i tend to ignore. 

is this error visible on the screen, or are you reading this from a log file or running the script from the console?

**Comment by Itsrainbowgirl** [comment]
it's visible on screen. I mean, after every video played it is printed on console screen.

**Comment by JuliusCode** [comment]
unfortunately it seems that the image failed to upload?

in principal, those error messages should go into a log file as the output of the script being started on boot, is redirected to a logfile

once you run the script independently in the console, those error messages will show up. 

the console commands to redirect can be seen in the console startup script, it is all the way at the end of „.bashrc“ in /home/pi

please note that the method of starting will change again soon, currently it is great for hacking but it lacks the long run stability, as the script is not restarted when it crashes
