### ISSUE TITLE
Automation triggering

### ISSUE THREAD

**Issue by ctaylor106** [JuliusCode/MP4MUSEUM#4]
Could there be a way to use a GPO or send a ethernet command to another device that would trigger at a certain point in the timeline of a video clip? Or is there a way to get the elapsed time of a clip to have another device to trigger a automation device? 

My client is wanting to play a video and then at time X trigger a curtain to open.

If this isn't already a feature I would be happy to sponsor the development of it.

All the Best,
Chase Taylor
Sound Vision Technical

**Comment by JuliusCode** [comment]
Dear Chase,

this would be possible by checking the current position of the player in the loop that waits for the end of the clip (line 41).
you can see how the script checks the state of the player, similarly, one can check the position of the player.

from what you are writing it would seems to me as it would need to be solved by hacking the script- it is not really a feature that could be used easily by "end-users" as you need to program timings and actions in the python script.

in the days of running dvd players in exhibitions i used an extra sound channel for a trigger-beep, maybe that's an option for you as well

best, Julius.
