### ISSUE TITLE
First attempt to boot fails

### ISSUE THREAD

**Issue by asebire** [JuliusCode/MP4MUSEUM#41]
Hello, I'm an artist really stretching my tech knowledge here but managed to flash mp4museum-v6.img to a 16GB SD on a Mac. Now, inserted into the RPi4 on the first boot, the second black screen flashes up text something like (using OCR, so a few typos, sorry!)

e2fsck 1.44.5 (15-Bcc-2018)
roatis: clean, 61216/201000 files. 515819/006912 blacks
8.622197) firstrum.sht3031: grep: rete/lightds/lightdn.comf: ho such file or directary
8.6873311 firstrum.sh3931:
me: cannat remoue boot/firstrum.sh°: Read-anly file systen
8.6968081 firstrun.sh3931: sed: couldn't open temporary file /boat/sedgbut?: Read-only file systen

![IMG_8728](https://github.com/JuliusCode/MP4MUSEUM/assets/155253678/d8d27aaa-fb80-4f1d-8759-97530b443ced)

Just wondering if there is there any easy solution please?
Thanks!
Adam

**Comment by JuliusCode** [comment]
Hi Adam,
from what i can guess reading the screenshot, it is not mp4museum that has been written onto the card, or something was added to the systems boot process somehow.

after writing the image using a mac, you should see a boot and a media partition. look for a file called config.txt on the boot partition and open it, the first line should indicate that it is the config for mp4museum.

best, Julius.

**Comment by asebire** [comment]
Thanks Julius for the reply (and the project itself!)

>> Update: it worked on the 4th try.  This time I said "no" to the imager's offer of customisation, of verification, and immediately removed the microSD — rather than mount it on Mac first to add media.  One of these must have made the difference!  Thanks again! Adam.


Earlier I was writing:

No it's definitely the right one;
# mp4 museum config v6 is the first line of config.txt 

And there are 2 partitions: boot, which is MSDOS FAT32, 268MB and Media which is ExFAT 9.5GB

The boot volume has 46 visible items, only one of which is a folder; it's called overlays

I tried doing the whole process again using the RPi imager v1.8.4.
 
If there's no simple explanation or fix then I will try to buy another microSD card and try again!

**Comment by JuliusCode** [comment]
thank you for the update, it seems that raspberry pi imager has been updated… 
the customizing will fail as the script they write onto the card to change settings cannot proceed on a write protected system. i will try to update the instructions soon.

J.

**Comment by JuliusCode** [comment]
just a short answer on the pi5 compatibility: i would think it does not boot, as new hardware usually required a new os version and bootloader to work in the past.

J.
