### ISSUE TITLE
Ctrl & C does not open the text console

### ISSUE THREAD

**Issue by Tagurpidi** [JuliusCode/MP4MUSEUM#43]
Hello, I'm sorry, I'm rather sure this is not an issue, but a user problem.
I'm trying to change the volume of MP4 museum, but CTRL+C doesn't open the text console, it doesn't have any effect whatsoever. 
I am a carpenter at my museum, inevitably forced to solve the technical questions as well. MP4 museum in its simplicity has been a heaven-sent gift when it comes to players, but this time I really can't figure out what I'm doing wrong. Any advice is appreciated.

**Comment by JuliusCode** [comment]
hey, sorry for the delay, the building my studio is at got hit by a tornado… trying to get on top of things again.

if pressing ctrl-c repeatedly has no affect, you could try alt&f2 to get to another console. i hope this works as currently i have no setup to confirm that. maybe it is an older version?

best, julius

**Comment by Tagurpidi** [comment]
Hello, sorry it took me too a while to get to further testing.
I installed version 5 a new on a different Rasp. (both are pi 4 model B), but still no luck with Ctrl+C nor with alt+f2.
I still suspect I'm doing something wrong, or I don't have strong enough fingers to bush the keys or something :-P. 
I let it boot up till the video had started and then bushed Ctrl+C but tried the same also during boot up, with no result whatsoever.

**Comment by JuliusCode** [comment]
hi,
i have just now set up a few players on raspi1 and raspi 3b with v6, both ctrl+c and alt+f2 works there. maybe try a different keyboard?

best, julius

**Comment by Tagurpidi** [comment]
Installed version 6, very flashy I have to say :-)  and ctrl+C works!
I guess the alt+f2 not working with version 5 is a keyboard problem.

**Comment by Tagurpidi** [comment]
Installed version 6, very flashy I have to say :-)  and ctrl+C works!
I guess the alt+f2 not working with version 5 is my keyboard problem.
Thank You!
