### ISSUE TITLE
Support for 4K video in sync mode

### ISSUE THREAD

**Issue by tewson** [JuliusCode/MP4MUSEUM#45]
Hi. Is it correct to say that the sync mode doesn't support 4K videos because it uses omxplayer-sync which can only play up to 1080p (regardless of the Pi model)? As opposed to the standalone mode which uses VLC which can play higher resolutions on Pi 4+.

**Comment by JuliusCode** [comment]
hey,
unfortunatly, yes. omxplayer-sync is outdated with no alternative that i would know of. if you have any leads on this, please do share

best, julius

**Comment by tewson** [comment]
Thank you for replying so quickly. From my brief research I've found a library for programmatically controlling VLC in JavaScript which might be a good starting point. https://github.com/formix/vlcplayer-node

**Comment by JuliusCode** [comment]
thank you for the link, this is similar to python-vlc which currently runs mp4museum internally. unfortunatly i lack the skills to program a sync mode myself… 

cheers! J.
