### ISSUE TITLE
Play multichannel audio files over HDMI

### ISSUE THREAD

**Issue by Peyof** [JuliusCode/MP4MUSEUM#46]
Hi Julius,

Do you think it's possible to play a multichannel audio file (quad for example) via the HDMI output?

In my tests, only the first two channels came out of the HDMI.

Thanks, Julius,

**Comment by JuliusCode** [comment]
Hi,
so far i have not been able to use multichannel in mp4museum. theoretically it should be able to output 5.1 on hdmi but i lack the hardware to check.

but it is possible to use the mp4museum script on a raspbian image that has pulse audio installed, or start vlc directly from a console. then you can use an external soundcard for multichannel. 

best, Julius.
