### ISSUE TITLE
Won't boot

### ISSUE THREAD

**Issue by o0777** [JuliusCode/MP4MUSEUM#47]
Hi! 
I'm working with two RPI4 and managed to get one booted. But the second one wont boot and only ends up giving me a black screen. Tried reinstalling with multiple SD cards but always end up with the same problem. I'm really confused since it works perfectly with my first try. 

This is what I get before it goes black:

e2fsck 1.44.5 (15-Dec-2018)
rootfs: clean, 61246/204800 files, 545819/806912 blocks
Raspbian GNU/Linux 10 mpmuseum tty1
mpAmuseum login: pi (automatic login)
Last login: Fri Jun 23 10:42:46 BST 2023 on ttyi
Linux mpimuseum 5.10.103-8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64
The programs included with the Debian GNU Linux systen are free software: the exact distribution terms for each program are described in the individual files in /usr/share/doc/#/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent permitted by applicable law.
Wi-Fi is currently blocked by rtkill.
Use raspi-config to set the country before use.

Thank you already!

**Comment by JuliusCode** [comment]
hi,

is one of them a very recent one, or has it been booting a full raspbian os lately? it could be that a newer firmware stops working with the „old“ operating system that runs mp4museum, but i can only guess. 

the messages are the usual ones, but if video playback won‘t start at all, i have not experienced that on pi4. usually it wouldn‘t boot at all if firmware was too new.

best, Julius,

**Comment by rugor** [comment]
same issue for me on Raspberry Pi 3 Model B

Steps to reproduce:

Follow the [download instructions](https://mp4museum.org/download/) and boot instructions with the [provided disk image](https://mp4museum.org/mp4museum-v6.img.zip), then attempt to boot up the Pi and it crashes on boot with [similar error as above](https://github.com/JuliusCode/MP4MUSEUM/issues/47#issue-2317066400).

```
cat /proc/cpuinfo

processor	: 0
BogoMIPS	: 38.40
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 38.40
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 38.40
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
BogoMIPS	: 38.40
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Revision	: a02082
Serial		: 00000000f13ed6d5
Model		: Raspberry Pi 3 Model B Rev 1.2
```

**Comment by rugor** [comment]
Experienced the same error and found that not passing settings through to the disk image write in Raspberry Pi Disk Imager was the fix.

**Comment by JuliusCode** [comment]
thanks for the info, i will update the website.

cheers!
