### ISSUE TITLE
Raspberry Pi 4 composite out not working

### ISSUE THREAD

**Issue by jijiweb** [JuliusCode/MP4MUSEUM#48]
I am trying to get the composite out to work, but to no avail. I have tried all the recommended steps listed on 

https://mp4museum.org/video-howto/

and the from there linked raspberry pi documentation. 

On HDMI it runs fine, for the composite out I am only able to get distorted sound to the CRT. 
Any hints or known issues?

Thank you!

**Comment by JuliusCode** [comment]
Hey,from what you are describing, it could be that your cable does not connect the 4pin plug to the 3 plugs in the right way.it should be from „tip-ring-ring-shaft“ connected to left, right, ground, video.best, Julius.Am 23.08.2024 um 17:06 schrieb jijiweb ***@***.***>:﻿
I am trying to get the composite out to work, but to no avail. I have tried all the recommended steps listed on
https://mp4museum.org/video-howto/
and the from there linked raspberry pi documentation.
On HDMI it runs fine, for the composite out I am only able to get distorted sound to the CRT.
Any hints or known issues?
Thank you!
