### ISSUE TITLE
Length knows issues ?

### ISSUE THREAD

**Issue by cwe6279** [JuliusCode/MP4MUSEUM#49]
Hi , this is a great tool for Halloween and had it working for some files but it seems when I get to files over 20 minutes regardless of file size I only get a blank screen - are there any tweaks or know issues related to clip lengths ?

**Comment by JuliusCode** [comment]
hey,
there is no limitation in the script, it will just go through the list of files and pass them on to vlc player.
in your case, it could be that the files cannot be found by the script, or that vlc player will not play them back.
best, Julius.

**Comment by JuliusCode** [comment]
if you have an extra memorycard to spare, maybe try the current version? an old version might not support your drive format, the video format, or both 📽️

with config file, do you mean config.txt? current one is:

# mp4 museum config v6

disable_splash=1
avoid_warnings=1
gpu_mem=128
dtparam=audio=on
disable_overscan=1
bootcode_delay=5

# optional video and audio config:

# Ignore HDMI auto config, force 1080p at 60 hz
# this can fix problems with silly projectors or displays
# remove the # on all three lines below
#hdmi_ignore_cec=1
#hdmi_group=1
#hdmi_mode=16


# enable 4k with more than 30hz on raspi 4
# remove the # from the next line
#hdmi_enable_4kp60=1


# force UHD (2160p at 60Hz)
# remove the # on all three lines below
#hdmi_ignore_cec=1
#hdmi_group=1
#hdmi_mode=97

#force audio on hdmi
#hdmi_drive=2

**Comment by JuliusCode** [comment]
was fixed by using handbrake to encode.
