### ISSUE TITLE
break in the loop in mp4master

### ISSUE THREAD

**Issue by daveprenj** [JuliusCode/MP4MUSEUM#5]
Is there supposed to be a break in the loop when using MP4M-Sync-Master?  
 
When I run it it plays for a couple minutes, then there is a temporary break where I see the command line/see some  earlier commands that I assume ran as the raspberry pi booted up.  Its only there for a split second

thanks

**Comment by JuliusCode** [comment]
hi dave

with mp4museum-sync, the loop is setup inside the player. if you see the console (=text) that means the program has quit unexpected. 
does it do the same with the video that comes with the image? if not, you could try to re-encode your file. if yes, try to re-write the image, or a different sd card, a different pi, or any combination of the before mentioned ;)

best, Julius
