### ISSUE TITLE
Pause/Play of synced videos

### ISSUE THREAD

**Issue by Mateipegithub** [JuliusCode/MP4MUSEUM#50]
Hello Julius,

thank you for your work! I got two players working and syncing flawlessly. For a performance I would need to be able to pause the two videos and then after some time let them play on. I thought using the button play/pause button would be perfect but it's not working for me. Can you help? Is than an issue when playing in sync mode?

**Comment by JuliusCode** [comment]
Hi,
unfortunately the sync option does not allow for the use of pause and next buttons.
in the near future i will release another software that can be remote controlled via a website, it will playback almost in sync on identical hardware, and can be paused, stopped, changed for each player or many players at once.
let me know if you would like to beta test this software?

best, Julius

**Comment by Mateipegithub** [comment]
That sounds amazing, yes I would love to test it.

Best, Matei

**Comment by JuliusCode** [comment]
Dear Matei,
the new project is available as a beta version:
www.mp4performance.org
will check the file on the website on monday, but i am optimistic that it works ;) doing the first job with it this weekend.

but it looks that in long term i will have a new sync player, too. i will keep your suggestion in mind towards the buttons in sync mode.

best, julius
