### ISSUE TITLE
MP4MUSEUM v5 - XDG_RUNTIME_DIR not set in the environment

### ISSUE THREAD

**Issue by josephmwells** [JuliusCode/MP4MUSEUM#7]
Version: 5 beta 3
Video Encoding: 4kp60 h265 using Handbrake Preset from MP4Museum website

Problem: 

At the end of every video loop, the screen flashes to the console and I see the message:

`rc.local[472]: error: XDG_RUNTIME_DIR not set in the environment.`

The video resumes from the beginning after this error.

I have tried installing the image fresh from the website, and have encoded my video using the preset from the How to 4k section of the website. I have also made sure to add `hdmi_enable_4kp60=1` to my config.txt.

**Comment by JuliusCode** [comment]
Hi Joseph,

sorry for the long delay in answering, but the little time i had recently to work on the project i was trying to push development of the software.
i could not replicate your error, nor do i know what the error actually means :( i am not a programmer or linux admin.. while i did try to search for an explanation of XDG_RUNTIME i could not piece this together. i hope you found a solution for your problem.

best, Julius.
