### ISSUE TITLE
seamless playback V5

### ISSUE THREAD

**Issue by lessbones** [JuliusCode/MP4MUSEUM#8]
Hey, trying the new V5, everything is very nice, but the seamless playback gives a big lag in the video only at the end.  Maybe a whole second of frozen video while the audio loops perfectly under it.

I'm using an h264 export straight from davinci resolve, using their default settings-- haven't tried anything special with handbrake or any other settings yet, and running from the internal "MEDIA" partition as "loop.mp4"

I tried the sync version, and while it was better, there was still a stutter of a few frames with the same file--  any ideas?

thanks for this amazing software!

**Comment by JuliusCode** [comment]
hi,

seamless loop will give you different experiences, based on hardware and codec details.
the minimum would be the lack of a black screen in between.

to achieve better results, use handbrake to encode and try i-frames only with different bit rates.
there is a box for text-editing encoding options, the magic is in there, or use ffmpeg on command line.

last but not least, make a loop of your loop of > hour duration, so the lag doesnt occur on  every repetition.

best, Julius.
