### ISSUE TITLE
Audio lag on sync

### ISSUE THREAD

**Issue by Transmodulator** [JuliusCode/MP4MUSEUM#9]
Hi! I'm using mp4museum v5 sync and am having a problem where the video with audio in it is lagging, whereas the videos with no audio are running perfectly. I have 12 players that need sync, 3 of which contain audio. I'm testing with just 4 videos for now. I made a black video+audio file and added a player for just the audio (5 players, hoping I can have the audio in a video though for 4 players) but that player lags all the same while the videos with no audio run smooth in sync. To be clear, the file freezes repeatedly, but stays in sync. I have the audio at 160 bit rate, I've tried both AAC and MP3 codes, both HDMI and analog audio out. I'm using all the same Sandisk Ultra SD cards. I'm using all Raspberry Pi 2011.12.  Anyone else having this issue? Sorry if this is a little confusing, going on two days troubleshooting this. Thanks yall!

**Comment by JuliusCode** [comment]
Hi there,
what software are you using to export your mp4? this could be a muxing issue, that process where audio and video are written i to one stream. 
best, Julius.

**Comment by Transmodulator** [comment]
I have been using Adobe Media Encoder. But I also tried re-encoding with Handbrake with no change in the issue

**Comment by JuliusCode** [comment]
personally i don‘t use adobe media encoder, many people have written with problems related to the software. i would suggest to export in a production codec and feed that into handbrake or ffmpg directly. 

J.

**Comment by Transmodulator** [comment]
Okay I am encoding as prores now will report back. Though when I made the file with audio on it master, it didn't freeze up anymore, ran perfectly. Unfortunately the other two videos with audio still froze all the same.

**Comment by Transmodulator** [comment]
Of course, your guide holds up! I exported the videos which have audio out of Media Encoder as ProRes and then used handbrake to make them mp4 and everything is now working perfectly in sync. No one is the exception to media encoder being suspect. Thank you!
